
import HeaderTop from '@/components/HeaderTop'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderMain from '@/components/HeaderMain'
import Navbar from '@/components/Navbar'
const inter = Inter({ subsets: ['latin'] })
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
export const metadata: Metadata = {
  title: 'GRocery SHop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        {children}</body>
    </html>
  )
}
